[package]
name = "ncm_dump"
version = "0.1.0"
edition = "2024"

[dependencies]
json = "=0.12.4"

[package.metadata.scripts]
run = "cargo run"
check = "cargo check"
build = "cargo build"
release = "cargo build --release"
test = "cargo test"